apiVersion: v1
kind: Pod
metadata:
  generateName: kueue-sleep-
  labels:
    kueue.x-k8s.io/queue-name: user-queue
spec:
  containers:
    - name: sleep
      image: busybox
      command:
        - sleep
      args:
        - 3600s
      resources:
        requests:
          cpu: 3
      env:
        - name: DEMO
          value: "Hello from the environment"
        - name: DEMO
          value: "Such a sweet sorrow"
  restartPolicy: OnFailure