name: Add issues by user to KDEV project
run-name: Add @${{github.event.inputs.gh_user}} issues
on:
  workflow_dispatch:
    inputs:
      gh_repo:
        description: 'Repository name'
        required: true
        default: 'kubernetes-sigs/kueue'
      gh_user:
        description: 'Assignee'
        required: true
        default: trasc
        type: choice
        options:
          - trasc
          - mcariatm
          - akranga
          - oginskis

jobs:
  Add-Issue-to-KDEV:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN_PROJECT_ACCESS }}
      # KDEV
      PROJECT_ID: PVT_kwDOABhCKs4APR3F
      GITHUB_USER: ${{github.event.inputs.gh_user}}
    steps: 
    - name: Get ${{github.event.inputs.gh_user}} issues
      id: issues
      run: gh api  'repos/${{github.event.inputs.gh_repo}}/issues?state=open&assignee=${{env.GITHUB_USER}}' -q '.[].node_id' | xargs
    - name: Add to KDEV
      env:
        ISSUES: ${{ steps.issues.outputs.stdout }}
      run: | 
        for issue in ${{ steps.issues.outputs.stdout }}; do
          gh api graphql -f query='
            mutation($project:ID!, $content:ID!) {
              addProjectV2ItemById(input: {projectId: $project contentId: $content}) {
                item {
                  id
                }
              }
            }'  -f project=$PROJECT_ID -f content=$issue
        done
