name: Add issue to KDEV project
on:
  workflow_dispatch:
    inputs:
      issue_repo:
        description: 'Repository name'
        required: true
        default: 'kubernetes-sigs/kueue'
      issue_num:
        description: 'Issue number'
        required: true

jobs:
  Add-Issue-to-KDEV:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN_PROJECT_ACCESS }}
      # KDEV
      PROJECT_ID: PVT_kwDOABhCKs4APR3F
    steps: 
    - name: Get Issue ID
      run: echo issue_node_id=$(gh api -q '.node_id' "repos/${{github.event.inputs.issue_repo}}/issues/${{github.event.inputs.issue_num}}") >> $GITHUB_ENV
    - name: Add issue to KDEV
      run: |
        gh api graphql -f query='
          mutation($project:ID!, $content:ID!) {
            addProjectV2ItemById(input: {projectId: $project contentId: $content}) {
              item {
                id
              }
            }
          }'  -f project=$PROJECT_ID -f content=${{env.issue_node_id}}
