name: Add issues by user to KDEV project
on:
  workflow_dispatch:
    inputs:
      gh_repo:
        description: 'Repository name'
        required: true
        default: 'kubernetes-sigs/kueue'
      gh_user:
        description: 'Assignee'
        required: true
        default: 'trasc'
        type: choice
        options:
          - trasc
          - mcariatm
          - akranga
          - oginskis

jobs:
  Add-Issue-to-KDEV:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN_PROJECT_ACCESS }}
      # KDEV
      PROJECT_ID: PVT_kwDOABhCKs4APR3F
      GITHUB_USER: ${{github.event.inputs.gh_user}}
    steps: 
    - name: Get issues by user
      run: ${{env.GITHUB_USER}}_issues=$(gh api  'repos/${{github.event.inputs.gh_repo}}/issues?state=open&assignee=${{env.GITHUB_USER}}' -q '.[].node_id' | xargs) >> $GITHUB_ENV
    - name: Add issues to KDEV
      run: |
        for issue in ${{env.GITHUB_USER}}_issues; do
          gh api graphql -f query='
            mutation($project:ID!, $content:ID!) {
              addProjectV2ItemById(input: {projectId: $project contentId: $content}) {
                item {
                  id
                }
              }
            }'  -f project=$PROJECT_ID -f content=$issue
        done
